universe_mock = {
    "name": "StarRail Trailblazers",
    "roundName": "Trial 1",
    "roundEndIn": 10650,
    "ship": {
        "fuelUsed": 0,
        "planet": {
            "name": "Earth",
            "garbage": {}
        },
        "capacityX": 8,
        "capacityY": 11,
        "garbage": {}
    },
    "universe": [
        [
            "Earth",
            "Moen",
            34
        ],
        [
            "Moen",
            "Earth",
            99
        ],
        [
            "Moen",
            "Krajcik",
            91
        ],
        [
            "Moen",
            "Hilpert-136",
            38
        ],
        [
            "Moen",
            "IPFJHUGD0",
            19
        ],
        [
            "Krajcik",
            "Moen",
            20
        ],
        [
            "Krajcik",
            "Hahn-229",
            59
        ],
        [
            "Krajcik",
            "Wunsch",
            45
        ],
        [
            "Hilpert-136",
            "PerfectAnt",
            9
        ],
        [
            "Hilpert-136",
            "Paucek-269",
            70
        ],
        [
            "IPFJHUGD0",
            "KAZPFH869",
            5
        ],
        [
            "Hahn-229",
            "Krajcik",
            14
        ],
        [
            "Hahn-229",
            "Zulauf-73",
            57
        ],
        [
            "Hahn-229",
            "Conroy",
            43
        ],
        [
            "Hahn-229",
            "Hickle-110",
            68
        ],
        [
            "Wunsch",
            "Krajcik",
            37
        ],
        [
            "Wunsch",
            "ModelStander08",
            28
        ],
        [
            "PerfectAnt",
            "Hilpert-136",
            14
        ],
        [
            "PerfectAnt",
            "Corkery-25",
            28
        ],
        [
            "Paucek-269",
            "ClementineFrail",
            95
        ],
        [
            "KAZPFH869",
            "IPFJHUGD0",
            33
        ],
        [
            "KAZPFH869",
            "Schmeler-280",
            54
        ],
        [
            "KAZPFH869",
            "CurrantImpromptu",
            57
        ],
        [
            "KAZPFH869",
            "Anderson-285",
            37
        ],
        [
            "Zulauf-73",
            "Hahn-229",
            59
        ],
        [
            "Zulauf-73",
            "HandsomeBill",
            41
        ],
        [
            "Zulauf-73",
            "Hintz",
            54
        ],
        [
            "Zulauf-73",
            "Ferry",
            24
        ],
        [
            "Conroy",
            "Hahn-229",
            20
        ],
        [
            "Conroy",
            "GownCuter",
            4
        ],
        [
            "Hickle-110",
            "BilberryMysterious",
            69
        ],
        [
            "ModelStander08",
            "Wunsch",
            61
        ],
        [
            "ModelStander08",
            "FancyBones",
            22
        ],
        [
            "ModelStander08",
            "Kozey",
            22
        ],
        [
            "Corkery-25",
            "PerfectAnt",
            15
        ],
        [
            "Corkery-25",
            "0MRJEYKC5",
            69
        ],
        [
            "Corkery-25",
            "Aufderhar-182",
            97
        ],
        [
            "Corkery-25",
            "Conn",
            13
        ],
        [
            "ClementineFrail",
            "Paucek-269",
            41
        ],
        [
            "ClementineFrail",
            "Pfannerstill",
            81
        ],
        [
            "ClementineFrail",
            "Ritchie",
            16
        ],
        [
            "ClementineFrail",
            "Marquardt",
            59
        ],
        [
            "Schmeler-280",
            "KAZPFH869",
            94
        ],
        [
            "Schmeler-280",
            "Boyle-136",
            85
        ],
        [
            "Schmeler-280",
            "5M4WW68P2",
            83
        ],
        [
            "Schmeler-280",
            "Lockman-222",
            65
        ],
        [
            "CurrantImpromptu",
            "Windler",
            45
        ],
        [
            "Anderson-285",
            "Mohr",
            36
        ],
        [
            "Anderson-285",
            "ClementineBusy",
            36
        ],
        [
            "HandsomeBill",
            "Zulauf-73",
            90
        ],
        [
            "HandsomeBill",
            "RefrigeratorEater01",
            92
        ],
        [
            "HandsomeBill",
            "Haag-280",
            94
        ],
        [
            "Hintz",
            "Hyatt-138",
            7
        ],
        [
            "Hintz",
            "HDJJ79E02",
            28
        ],
        [
            "Ferry",
            "Dibbert",
            99
        ],
        [
            "GownCuter",
            "Conroy",
            33
        ],
        [
            "GownCuter",
            "RaspberryCareful",
            65
        ],
        [
            "GownCuter",
            "Fadel",
            7
        ],
        [
            "GownCuter",
            "CYB11NPJ0",
            99
        ],
        [
            "BilberryMysterious",
            "Hickle-110",
            40
        ],
        [
            "BilberryMysterious",
            "Hackett",
            7
        ],
        [
            "BilberryMysterious",
            "Wolff",
            18
        ],
        [
            "FancyBones",
            "ModelStander08",
            34
        ],
        [
            "FancyBones",
            "UncleFighter4",
            56
        ],
        [
            "Kozey",
            "Pagac",
            14
        ],
        [
            "0MRJEYKC5",
            "Corkery-25",
            96
        ],
        [
            "0MRJEYKC5",
            "YABMNUDC0",
            73
        ],
        [
            "0MRJEYKC5",
            "Paucek",
            53
        ],
        [
            "Aufderhar-182",
            "Barrows",
            92
        ],
        [
            "Conn",
            "Corkery-25",
            7
        ],
        [
            "Conn",
            "Keebler",
            59
        ],
        [
            "Conn",
            "Reynolds",
            31
        ],
        [
            "Pfannerstill",
            "ClementineFrail",
            61
        ],
        [
            "Pfannerstill",
            "HelpfulTie",
            15
        ],
        [
            "Ritchie",
            "ClementineFrail",
            4
        ],
        [
            "Ritchie",
            "DuBuque",
            41
        ],
        [
            "Ritchie",
            "VonRueden-279",
            94
        ],
        [
            "Marquardt",
            "Block",
            71
        ],
        [
            "Boyle-136",
            "Schmeler-280",
            90
        ],
        [
            "Boyle-136",
            "Prohaska-250",
            63
        ],
        [
            "Boyle-136",
            "Leffler",
            27
        ],
        [
            "Boyle-136",
            "GlamorousCicada",
            99
        ],
        [
            "5M4WW68P2",
            "Schmeler-280",
            40
        ],
        [
            "5M4WW68P2",
            "BucketClaper",
            33
        ],
        [
            "5M4WW68P2",
            "Streich",
            11
        ],
        [
            "5M4WW68P2",
            "Collier-274",
            68
        ],
        [
            "Lockman-222",
            "Schultz",
            30
        ],
        [
            "Lockman-222",
            "XTTSPD764",
            47
        ],
        [
            "Lockman-222",
            "Blanda-240",
            67
        ],
        [
            "Windler",
            "CurrantImpromptu",
            20
        ],
        [
            "Windler",
            "Rohan",
            54
        ],
        [
            "Windler",
            "Hartmann-253",
            57
        ],
        [
            "Mohr",
            "Anderson-285",
            83
        ],
        [
            "Mohr",
            "PuzzledNeck",
            48
        ],
        [
            "Mohr",
            "Schaden-35",
            50
        ],
        [
            "Mohr",
            "BlueberryOdd",
            68
        ],
        [
            "ClementineBusy",
            "Anderson-285",
            64
        ],
        [
            "ClementineBusy",
            "Jaskolski",
            96
        ],
        [
            "RefrigeratorEater01",
            "HandsomeBill",
            71
        ],
        [
            "RefrigeratorEater01",
            "Schneider-162",
            88
        ],
        [
            "RefrigeratorEater01",
            "BagCrawler",
            97
        ],
        [
            "RefrigeratorEater01",
            "Runolfsdottir",
            13
        ],
        [
            "Haag-280",
            "CherimoyaInquiring",
            53
        ],
        [
            "Haag-280",
            "7B09B9OG8",
            51
        ],
        [
            "Haag-280",
            "PeacockHuger",
            74
        ],
        [
            "Hyatt-138",
            "Hintz",
            3
        ],
        [
            "Hyatt-138",
            "Bins-25",
            99
        ],
        [
            "HDJJ79E02",
            "Hintz",
            8
        ],
        [
            "HDJJ79E02",
            "Price",
            86
        ],
        [
            "Dibbert",
            "Ferry",
            33
        ],
        [
            "Dibbert",
            "CatRideer63",
            79
        ],
        [
            "Dibbert",
            "SuperDog",
            3
        ],
        [
            "Dibbert",
            "Hegmann",
            46
        ],
        [
            "RaspberryCareful",
            "GownCuter",
            39
        ],
        [
            "RaspberryCareful",
            "Daniel",
            43
        ],
        [
            "RaspberryCareful",
            "Wintheiser",
            4
        ],
        [
            "Fadel",
            "HornRideer",
            94
        ],
        [
            "CYB11NPJ0",
            "GownCuter",
            53
        ],
        [
            "CYB11NPJ0",
            "Mraz",
            90
        ],
        [
            "Hackett",
            "BilberryMysterious",
            85
        ],
        [
            "Hackett",
            "Cassin",
            22
        ],
        [
            "Hackett",
            "Lemke",
            62
        ],
        [
            "Wolff",
            "AloofWombat7",
            88
        ],
        [
            "UncleFighter4",
            "FancyBones",
            39
        ],
        [
            "UncleFighter4",
            "W7IGDGW51",
            96
        ],
        [
            "Pagac",
            "Kozey",
            88
        ],
        [
            "Pagac",
            "EOIOQ39V1",
            38
        ],
        [
            "YABMNUDC0",
            "0MRJEYKC5",
            28
        ],
        [
            "YABMNUDC0",
            "AZH4DE3G4",
            85
        ],
        [
            "Paucek",
            "Feeney",
            11
        ],
        [
            "Paucek",
            "Heaney",
            41
        ],
        [
            "Barrows",
            "Aufderhar-182",
            6
        ],
        [
            "Barrows",
            "Pacocha",
            88
        ],
        [
            "Keebler",
            "Conn",
            69
        ],
        [
            "Keebler",
            "Beier",
            3
        ],
        [
            "Reynolds",
            "Eden",
            44
        ],
        [
            "HelpfulTie",
            "Pfannerstill",
            59
        ],
        [
            "DuBuque",
            "Ritchie",
            94
        ],
        [
            "DuBuque",
            "VonRueden-279",
            58
        ],
        [
            "VonRueden-279",
            "UncleFighter4",
            9
        ],
        [
            "Block",
            "Marquardt",
            5
        ],
        [
            "Block",
            "UncleFighter4",
            63
        ],
        [
            "Prohaska-250",
            "Boyle-136",
            88
        ],
        [
            "Prohaska-250",
            "Leffler",
            45
        ],
        [
            "Leffler",
            "GlamorousCicada",
            5
        ],
        [
            "GlamorousCicada",
            "Mraz",
            32
        ],
        [
            "BucketClaper",
            "5M4WW68P2",
            82
        ],
        [
            "BucketClaper",
            "Streich",
            73
        ],
        [
            "Streich",
            "Collier-274",
            26
        ],
        [
            "Collier-274",
            "HandsomeBill",
            24
        ],
        [
            "Schultz",
            "Lockman-222",
            90
        ],
        [
            "Schultz",
            "XTTSPD764",
            80
        ],
        [
            "XTTSPD764",
            "Blanda-240",
            18
        ],
        [
            "Blanda-240",
            "Moen",
            73
        ],
        [
            "Rohan",
            "Windler",
            11
        ],
        [
            "Rohan",
            "Hartmann-253",
            77
        ],
        [
            "Hartmann-253",
            "Windler",
            44
        ],
        [
            "Hartmann-253",
            "Krajcik",
            62
        ],
        [
            "PuzzledNeck",
            "Mohr",
            78
        ],
        [
            "PuzzledNeck",
            "Schaden-35",
            58
        ],
        [
            "Schaden-35",
            "BlueberryOdd",
            14
        ],
        [
            "BlueberryOdd",
            "Mohr",
            39
        ],
        [
            "BlueberryOdd",
            "Krajcik",
            66
        ],
        [
            "Jaskolski",
            "ClementineBusy",
            82
        ],
        [
            "Schneider-162",
            "RefrigeratorEater01",
            15
        ],
        [
            "Schneider-162",
            "BagCrawler",
            35
        ],
        [
            "BagCrawler",
            "RefrigeratorEater01",
            24
        ],
        [
            "BagCrawler",
            "Runolfsdottir",
            43
        ],
        [
            "Runolfsdottir",
            "RefrigeratorEater01",
            52
        ],
        [
            "CherimoyaInquiring",
            "Haag-280",
            49
        ],
        [
            "CherimoyaInquiring",
            "7B09B9OG8",
            97
        ],
        [
            "7B09B9OG8",
            "PeacockHuger",
            30
        ],
        [
            "PeacockHuger",
            "Haag-280",
            56
        ],
        [
            "PeacockHuger",
            "Krajcik",
            30
        ],
        [
            "Bins-25",
            "Hyatt-138",
            88
        ],
        [
            "Bins-25",
            "HandsomeBill",
            45
        ],
        [
            "Price",
            "HDJJ79E02",
            92
        ],
        [
            "CatRideer63",
            "Dibbert",
            32
        ],
        [
            "CatRideer63",
            "SuperDog",
            76
        ],
        [
            "SuperDog",
            "Hegmann",
            21
        ],
        [
            "Hegmann",
            "Dibbert",
            21
        ],
        [
            "Hegmann",
            "BagCrawler",
            49
        ],
        [
            "Daniel",
            "RaspberryCareful",
            80
        ],
        [
            "Daniel",
            "Wintheiser",
            3
        ],
        [
            "Wintheiser",
            "RaspberryCareful",
            32
        ],
        [
            "HornRideer",
            "Fadel",
            89
        ],
        [
            "HornRideer",
            "Runolfsdottir",
            38
        ],
        [
            "Mraz",
            "CYB11NPJ0",
            8
        ],
        [
            "Cassin",
            "Hackett",
            33
        ],
        [
            "Cassin",
            "Lemke",
            48
        ],
        [
            "Lemke",
            "CYB11NPJ0",
            62
        ],
        [
            "AloofWombat7",
            "Wolff",
            77
        ],
        [
            "AloofWombat7",
            "CYB11NPJ0",
            34
        ],
        [
            "W7IGDGW51",
            "UncleFighter4",
            4
        ],
        [
            "EOIOQ39V1",
            "Pagac",
            24
        ],
        [
            "EOIOQ39V1",
            "UncleFighter4",
            83
        ],
        [
            "AZH4DE3G4",
            "YABMNUDC0",
            3
        ],
        [
            "AZH4DE3G4",
            "Wunsch",
            87
        ],
        [
            "Feeney",
            "Paucek",
            26
        ],
        [
            "Feeney",
            "Heaney",
            13
        ],
        [
            "Heaney",
            "Wunsch",
            30
        ],
        [
            "Pacocha",
            "Barrows",
            47
        ],
        [
            "Pacocha",
            "HandsomeBill",
            6
        ],
        [
            "Beier",
            "Keebler",
            85
        ],
        [
            "Eden",
            "Reynolds",
            78
        ],
        [
            "Eden",
            "Krajcik",
            61
        ]
    ],
    "attempt": 1
}

collect_mock = {
  "leaved": []
}

travel_mock = {
    "planetGarbage": {
        "2FvakD": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                3,
                1
            ],
            [
                2,
                2
            ]
        ],
        "2FvbCi": [
            [
                0,
                1
            ],
            [
                0,
                0
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ]
        ],
        "2FvvP1": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                0,
                0
            ],
            [
                1,
                2
            ],
            [
                2,
                2
            ],
            [
                2,
                1
            ]
        ],
        "2FwFZJ": [
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                0
            ],
            [
                2,
                1
            ],
            [
                3,
                1
            ]
        ],
        "2FwG63": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ]
        ],
        "2FwbGL": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ],
            [
                1,
                3
            ]
        ],
        "2Fwbiq": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ],
            [
                0,
                1
            ],
            [
                3,
                1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ],
            [
                1,
                3
            ]
        ],
        "2Fwvu8": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                2
            ],
            [
                2,
                2
            ],
            [
                2,
                3
            ],
            [
                3,
                3
            ]
        ],
        "2FxG5R": [
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                0
            ],
            [
                2,
                1
            ],
            [
                3,
                1
            ]
        ],
        "2FxGXv": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                1,
                2
            ],
            [
                1,
                3
            ],
            [
                2,
                3
            ],
            [
                3,
                3
            ]
        ],
        "2FxbiD": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                0,
                1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ],
            [
                2,
                2
            ],
            [
                3,
                2
            ],
            [
                2,
                3
            ]
        ],
        "2FxcAi": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ]
        ],
        "HXLk": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ],
            [
                0,
                1
            ],
            [
                0,
                2
            ],
            [
                1,
                2
            ],
            [
                2,
                2
            ],
            [
                0,
                3
            ],
            [
                2,
                3
            ]
        ],
        "HXoF": [
            [
                0,
                2
            ],
            [
                1,
                2
            ],
            [
                1,
                1
            ],
            [
                1,
                0
            ],
            [
                2,
                2
            ],
            [
                3,
                2
            ]
        ],
        "HryY": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                0
            ],
            [
                2,
                1
            ]
        ],
        "HsS3": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                0,
                0
            ],
            [
                1,
                2
            ],
            [
                1,
                1
            ]
        ],
        "JCcL": [
            [
                0,
                0
            ],
            [
                1,
                0
            ]
        ],
        "JXnd": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                0,
                0
            ],
            [
                1,
                2
            ],
            [
                1,
                0
            ],
            [
                2,
                2
            ],
            [
                3,
                2
            ]
        ],
        "JYF8": [
            [
                0,
                3
            ],
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                1,
                3
            ],
            [
                1,
                1
            ],
            [
                2,
                3
            ],
            [
                2,
                1
            ],
            [
                3,
                3
            ],
            [
                3,
                2
            ],
            [
                3,
                1
            ],
            [
                3,
                0
            ]
        ],
        "JsRR": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ],
            [
                0,
                1
            ],
            [
                2,
                1
            ],
            [
                2,
                2
            ],
            [
                3,
                2
            ]
        ],
        "Jssv": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                0,
                0
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                3,
                1
            ],
            [
                3,
                0
            ]
        ],
        "KD8T": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ]
        ],
        "KYJk": [
            [
                0,
                0
            ],
            [
                1,
                0
            ],
            [
                2,
                0
            ],
            [
                3,
                0
            ],
            [
                0,
                1
            ],
            [
                3,
                1
            ]
        ],
        "KYmF": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                0,
                2
            ],
            [
                2,
                2
            ],
            [
                3,
                2
            ],
            [
                2,
                3
            ]
        ],
        "KswY": [
            [
                0,
                2
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                0
            ],
            [
                2,
                1
            ],
            [
                3,
                1
            ]
        ],
        "LD7q": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                1,
                2
            ]
        ],
        "LDaL": [
            [
                0,
                0
            ],
            [
                0,
                1
            ],
            [
                1,
                1
            ],
            [
                2,
                1
            ],
            [
                0,
                2
            ],
            [
                2,
                2
            ],
            [
                0,
                3
            ],
            [
                2,
                3
            ],
            [
                3,
                3
            ]
        ]
    },
    "shipGarbage": None,
    "fuelDiff": 34,
    "planetDiffs": [
        {
            "from": "Earth",
            "to": "Moen",
            "fuel": 44
        }
    ]
}
